name: xq_link
on: 
  push:
    branches:
      - 'xq-link'
defaults:
  run:
    shell: bash
jobs:
  xqerl-cli-crud-ops:
    runs-on: ubuntu-latest
    services:
       xq:
        image: grantmacken/alpine-xqerl
        ports:
          - 8081:8081
        options: >-
          --name xq
          --mount "type=volume,target=/user/local/xqerl/priv/static/assets,source=static-assets"
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: set up 
        run: |
          echo ' - set up xqerl project working environment'
          source .env
          echo -n ' - ${RUN_NAME} running: ' 
          docker container inspect -f '{{.State.Running}}' ${RUN_NAME}
          echo -n ' - xqerl application all started: '
          docker exec xq xqerl eval 'application:ensure_all_started(xqerl).' | grep -oP 'ok'
          mkdir -p $HOME/.local/bin
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          pushd $HOME/.local/bin && ln -s ${GITHUB_WORKSPACE}/bin/xq && popd
          make clean
          make escripts
          make main-modules
          echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com --username ${GITHUB_ACTOR} --password-stdin &> /dev/null
          make pull
      - name: Create [ xq link {file} ]
        run: |
          echo ' - examples of link creation'
          echo ' The `xq link` command will produce two outcomes.'
          echo '1. a binary asset on the static-assets container volume.' 
          echo '2. a db **link** to the file asset.' 
          echo ' The origin source may pass thru a "asset pipeline" ' 
          echo ' to produce a desired outcome like gzip compression' 
          printf %60s | tr ' ' '-' && echo
          echo '*example*: create db link to compressed svgz file.'
          echo '> xq link example.com icons/article.svg'
          xq link example.com icons/article.svg
          printf %60s | tr ' ' '-' && echo
          echo '*example*: create db link to gzipped js file'
          echo '> xq link example.com scripts/prism.js'
          xq link example.com scripts/prism.js
          printf %60s | tr ' ' '-' && echo
          echo '*example*: create db link to gzipped stylesheet'
          echo '> xq link example.com styles/index.css
          xq link example.com styles/index.css
          printf %60s | tr ' ' '-' && echo
          echo '*example*: create db link to font'
          echo '> xq link example.com fonts/ibm-plex-mono-v5-latin-regular.woff2'
          xq link example.com fonts/ibm-plex-mono-v5-latin-regular.woff2
          printf %60s | tr ' ' '-' && echo

